# Generated by Django 4.0.2 on 2022-10-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogOn', '0002_blog_title_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='userName',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
