# Generated by Django 4.0.2 on 2022-10-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogOn', '0003_rename_username_blog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
